What height is the best for the open?
maybe take the average score of each height?
 Given what I know about crossfit and that majority of workouts favor that of a smaller statue my guess is that around the 70 inch mark will be the suitable area

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as st
from IPython.display import display

df = pd.read_csv('Final_Mens_open21.1.csv')

pd.set_option('display.max_columns',None)
display(df.head(10))

,Unnamed: 0,Unnamed: 0.1,first_name,lastname,Placing,country,continent,Age,affiliate,points,Unnamed: 18,Body Weight in LBS,Body Height in inch,21.1 Placing,21.1 S or F,21.1 Completion time,21.1 Tiebreaker reps,21.2 Placing,21.2 S or F,21.2 Completion time,21.2 Tiebreaker reps,21.3 Placing,21.3 S or F,21.3 Completion time,21.3 Tiebreaker reps,21.4 Placing,21.4 S or F,21.4 Weight Lifted in lbs
0,0,0,JEFFREY,ADLER,1,Canada,North America,27,CrossFit Wonderland,101,NaN,197.00000,69.000000,20,NaN,11:55,NaN,8.0,NaN,9:14,NaN,27.0,NaN,8:15,NaN,46.0,NaN,317.0
1,1,1,SCOTT,PANCHIK,2,United States,North America,33,CrossFit Mentality,141,NaN,187.00000,69.000000,33,NaN,12:25,NaN,47.0,NaN,9:52,NaN,5.0,NaN,7:48,NaN,56.0,NaN,316.0
2,2,2,TRAVIS,MEAD,3,United States,North America,34,Iron Valley CrossFit,165,NaN,205.00000,73.000000,87,NaN,13:02,NaN,24.0,NaN,9:38,NaN,48.0,NaN,8:26,NaN,6.0,NaN,345.0
3,3,3,SAXON,PANCHIK,4,United States,North America,25,CrossFit Cliffside,217,NaN,180.00000,69.000000,5,NaN,11:25,NaN,68.0,NaN,9:59,NaN,87.0,NaN,8:41,NaN,57.0,NaN,316.0
4,4,4,RICHARD,FRONING JR.,5,United States,North America,33,CrossFit Mayhem,254,NaN,194.00000,69.000000,58,NaN,12:45,NaN,91.0,NaN,10:04,NaN,5.0,NaN,7:48,NaN,100.0,NaN,312.0
5,5,5,NOAH,OHLSEN,6,United States,North America,30,Peak 360 CrossFit,272,NaN,190.00000,67.000000,11,NaN,11:41,NaN,21.0,NaN,9:33,NaN,2.0,NaN,7:44,NaN,238.0,NaN,301.0
6,6,6,SAMUEL,COURNOYER,7,Canada,North America,25,CrossFit Mayhem,276,NaN,205.00000,70.866142,158,NaN,13:27,NaN,79.0,NaN,10:02,NaN,20.0,NaN,8:09,NaN,19.0,NaN,328.0
7,7,7,COLE,GREASHABER,8,United States,North America,21,CrossFit Lee's Summit (LS),403,NaN,206.00000,72.000000,82,NaN,13:01,NaN,68.0,NaN,9:59,NaN,46.0,NaN,8:25,NaN,207.0,NaN,303.0
8,8,8,AGUSTIN,RICHELME,9,Argentina,South America,24,NaN,417,NaN,182.98346,68.110236,30,NaN,12:19,NaN,137.0,NaN,10:15,NaN,1.0,NaN,7:40,NaN,249.0,NaN,300.0
9,9,9,OLEG,LASCENKO,10,United Kingdom,Europe,23,CrossFit Abu Dhabi,428,NaN,202.82504,68.897638,53,NaN,12:43,NaN,22.0,NaN,9:34,NaN,102.0,NaN,8:46,NaN,251.0,NaN,300.0

In [11]:
df['Body Height in inch']=df['Body Height in inch'].round(0)
df.iloc[57645:57655]

All_heights = df[df['Body Height in inch'].notna()]
All_heights.iloc[57645:57655]
#df.groupby(['Body Height in inch']).mean()

,Unnamed: 0,Unnamed: 0.1,first_name,lastname,Placing,country,continent,Age,affiliate,points,Unnamed: 18,Body Weight in LBS,Body Height in inch,21.1 Placing,21.1 S or F,21.1 Completion time,21.1 Tiebreaker reps,21.2 Placing,21.2 S or F,21.2 Completion time,21.2 Tiebreaker reps,21.3 Placing,21.3 S or F,21.3 Completion time,21.3 Tiebreaker reps,21.4 Placing,21.4 S or F,21.4 Weight Lifted in lbs
78527,78527,78527,ERIC,PHILLIPS,78528,United States,North America,33,CrossFit Donelson,306655,NaN,217.00000,78.0,85003,NaN,NaN,118.0,80942.0,NaN,NaN,180.0,74710.0,NaN,NaN,114.0,66000.0,NaN,165.0
78528,78528,78528,BOB,ADNEY,78529,United States,North America,44,Black Widow CrossFit,306659,NaN,190.00000,67.0,80722,NaN,NaN,169.0,81148.0,NaN,NaN,179.0,78438.0,NaN,NaN,100.0,66351.0,NaN,165.0
78529,78529,78529,DANIEL,KIENAST,78530,Austria,Europe,29,NaN,306670,NaN,218.25738,68.0,107584,s,NaN,386.0,82925.0,NaN,NaN,174.0,59777.0,s,NaN,135.0,56384.0,NaN,176.0
78531,78531,78531,ALAIN,SISON,78531,United States,North America,47,CrossFit Reform,306671,NaN,NaN,170.0,68741,NaN,NaN,214.0,87318.0,NaN,NaN,161.0,70550.0,NaN,NaN,120.0,80062.0,NaN,135.0
78532,78532,78532,ALEX,USHAKOV,78533,New Zealand,Oceania,41,H1 CrossFit,306673,NaN,158.73264,67.0,33021,NaN,NaN,359.0,36034.0,NaN,17:37,NaN,101151.0,NaN,NaN,NaN,136467.0,NaN,NaN
78533,78533,78533,STANLEY,ROSS,78534,South Africa,Africa,36,BarWolf CrossFit,306674,NaN,174.16498,74.0,90171,NaN,NaN,112.0,84409.0,NaN,NaN,170.0,72221.0,NaN,NaN,120.0,59873.0,NaN,174.0
78539,78539,78539,ANDREAS,JOHANSSON,78540,Sweden,Europe,36,Skelleftea CrossFit,306691,NaN,187.39270,72.0,91876,NaN,NaN,92.0,79339.0,NaN,NaN,183.0,64713.0,NaN,NaN,135.0,70763.0,NaN,155.0
78540,78540,78540,ÍÑIGO,GONZÁLEZ,78541,Spain,Europe,27,NaN,306694,NaN,154.32340,71.0,117347,NaN,NaN,NaN,72775.0,NaN,NaN,198.0,39010.0,NaN,NaN,143.0,77562.0,NaN,143.0
78541,78541,78541,RON,BEARL,78541,United States,North America,51,CrossFit St. Croix,306694,NaN,199.00000,68.0,102114,s,NaN,571.0,67703.0,NaN,NaN,210.0,68862.0,s,NaN,126.0,68015.0,NaN,160.0
78542,78542,78542,TRISTON,WELCH,78543,United States,North America,22,CrossFit Kemah,306699,NaN,170.00000,68.0,84622,NaN,NaN,119.0,82553.0,NaN,NaN,175.0,71056.0,NaN,NaN,120.0,68468.0,NaN,158.0