In [60]:
import pandas as pd
import numpy as np
from IPython.display import display

def kg_to_lbs(num):
    print(num.name)
    #print(type(num))
    if num.name=='Weight unit':
        print('begin here')
        print(num)
        print('num.nam 9 \n')
        print(num.values)
def rep_parse(x):
    #if x.iloc[1]=='(--)':
    #print(type(x))
    if type(x)==str and')' in x:
        #print(x)
        x = x[:4]
    return x
def s_f_parse(x):
    if type(x)==str and ')' in x:
        x = x[:1]
    return x
def sep_time(x):
    if type(x)==str and ':' not in x:
        x = None
    return x 
def sep_unfin(x):
    if type(x)==str and (':' in x or '--' in x):
        x = None
    return x

pd.set_option('display.max_columns',None) #this is to show all columns
#def score_parse(x):
 #   if type(x)==str and ':' in x:
def parse_wkout(workout):
    score211 = Mens_data[workout].str.split(" ",5,expand=True)
    score211[0]=score211[0].str.extract('(\d+)',expand=False)#takes off the "th" and "nd" at end of numbers (getss all numeric values)
    score211[1]=score211[1].str.extract('\(([^)]+)',expand=False)#grabs everything in parenthasis
    score211[5] = score211[1].apply(sep_time)
    score211[6] = score211[1].apply(sep_unfin)
    score211[2] = score211[2].apply(rep_parse)
    score211[3] = score211[3].apply(s_f_parse)
    score211[4] = score211[4].apply(s_f_parse)
    score211[4].fillna(score211[3],inplace=True)
    score211.drop(score211.columns[3],axis=1,inplace=True) #drop third column in table referenced by the index
    score211.drop(score211.columns[1],axis=1,inplace=True)
    return score211
        
#Mens_data = pd.read_csv('test_open_men.csv')
Mens_data = pd.read_csv('men_open_21.1.csv')

Mens_data['Age'] = Mens_data['Age'].str.extract('(\d+)',expand=False)

height_and_weight = Mens_data['Height and Weight'].str.split("|",1,expand=True)
Mens_data['Height'] = height_and_weight[0]
Mens_data['Weight'] = height_and_weight[1]

height_and_unit=Mens_data['Height'].str.split(" ",1,expand=True)
Mens_data['Height']=height_and_unit[0].astype(float)
Mens_data['Height unit']=height_and_unit[1]
#bill.head(10)
weight_and_unit=Mens_data['Weight'].str.split(" ",2,expand=True)
#there is an extra space after the pipe
Mens_data['Weight']=weight_and_unit[1].astype(float)
Mens_data['Weight unit']=weight_and_unit[2]
Mens_data.head(10)
#test = Mens_data.where(Mens_data['Weight unit']=='kg')['Weight'].astype(int)


Mens_data['New Kg weight']= Mens_data.where(Mens_data['Weight unit']=='kg').apply(lambda x: x*2.20462 if x.name=='Weight'else x)['Weight']
Mens_data['New Kg weight'].fillna(Mens_data['Weight'],inplace=True)
Mens_data['Body Weight in LBS'] = Mens_data['New Kg weight']
Mens_data=Mens_data.drop(['Weight','Weight unit','New Kg weight','Height and Weight'],axis=1)
#Mens_data.where(Mens_data['Weight unit']=='kg').apply(kg_to_lbs)

Mens_data['New cm height']= Mens_data.where(Mens_data['Height unit']=='cm ').apply(lambda x: x/2.54 if x.name=='Height'else x)['Height']
Mens_data['New cm height'].fillna(Mens_data['Height'],inplace=True)
Mens_data['Body Height in inch'] = Mens_data['New cm height']
Mens_data=Mens_data.drop(['Height','Height unit','New cm height'],axis=1)
#display(Mens_data.head(10))


New_211 = parse_wkout('21.1')
Mens_data.drop(columns=['21.1','21.1 time'],inplace=True)
Mens_data['21.1 Placing'] = New_211[0]
Mens_data['21.1 S or F'] = New_211[4]
Mens_data['21.1 Completion time'] = New_211[5]
Mens_data['21.1 Tiebreaker reps'] = New_211[6]

#0 is 211 placing
#4 scaled of fixed
#5 completion time
#6 Tiebreaker reps
New_212 = parse_wkout('21.2')
Mens_data.drop(columns=['21.2','21.2 time'],inplace=True)
Mens_data['21.2 Placing'] = New_212[0]
Mens_data['21.2 S or F'] = New_212[4]
Mens_data['21.2 Completion time'] = New_212[5]
Mens_data['21.2 Tiebreaker reps'] = New_212[6]


New_213 = parse_wkout('21.3')
Mens_data.drop(columns=['21.3','21.3 time'],inplace=True)
Mens_data['21.3 Placing'] = New_213[0]
Mens_data['21.3 S or F'] = New_211[4]
Mens_data['21.3 Completion time'] = New_213[5]
Mens_data['21.3 Tiebreaker reps'] = New_213[6]
#display(Mens_data.head(10))

New_214 = parse_wkout('21.4')
Mens_data.drop(columns=['21.4','weight'],inplace=True)
Mens_data['21.4 Placing'] = New_214[0]
Mens_data['21.4 S or F'] = New_214[4]
Mens_data['21.4 Weight Lifted in lbs'] = New_214[6]
#print(score21144)
#print(len(score211))
#place211 = score211[0]



#score212

#if ' (--)' != score211[1] :#and ':' not in score211[1]:
 #   reps211 = score211[2]
  #  print('we have exception')
#    print(score211[4])

#KG=Mens_data[Mens_data['Weight unit']=='kg']
#KG.head(10)
#test.head(10)
display(New_214)
display(Mens_data.head(40))

         0     2     4     5     6
0    99667   lbs     f  None   100
1    99534   lbs     f  None   115
2    99862   lbs     f  None    66
3    99995   lbs     f  None    35
4   116079  None  None  None  None
5   104207  None  None  None  None
6    99593   lbs     f  None   110
7   100003   lbs     f  None    30
8   100081  None  None  None  None
9   104207   lbs     s  None     0
10  106863  None  None  None  None
11  134707  None  None  None  None
12  113486  None  None  None  None
13   99580   lbs     f  None   110
14  132298  None  None  None  None
15   99486   lbs     f  None   120
16   99685   lbs     f  None    99
17  131520  None  None  None  None
18  116079  None  None  None  None
19   99607   lbs     f  None   110
20   99827   lbs     f  None    75
21  121142  None  None  None  None
22   99913   lbs     f  None    55
23  121142  None  None  None  None
24  113486  None  None  None  None
25  129404  None  None  None  None
26   99805   lbs     f  None    81
27  100002   lbs     f  None    30
28   99635   lbs     f  None   105
29  116476  None  None  None  None
30  105764  None  None  None  None
31   99834   lbs     f  None    72
32  115649  None  None  None  None
33   99836   lbs     f  None    71
34  123688  None  None  None  None
35   99852   lbs     f  None    67
36   99606   lbs     f  None   110
37  104207  None  None  None  None
38  104207  None  None  None  None
39  124863  None  None  None  None
40  121142  None  None  None  None
41  105764  None  None  None  None
42  126325  None  None  None  None
43  121850  None  None  None  None
44  121850  None  None  None  None
45  105764  None  None  None  None
46  119268  None  None  None  None
47   99819   lbs     f  None    77
48  117943  None  None  None  None
49   99939   lbs     f  None    46

,Unnamed: 0,first_name,lastname,Placing,country,continent,Age,affiliate,points,Body Weight in LBS,Body Height in inch,21.1 Placing,21.1 S or F,21.1 Completion time,21.1 Tiebreaker reps,21.2 Placing,21.2 S or F,21.2 Completion time,21.2 Tiebreaker reps,21.3 Placing,21.3 S or F,21.3 Completion time,21.3 Tiebreaker reps,21.4 Placing,21.4 S or F,21.4 Weight Lifted in lbs
0,0,ARMANDO,FELIX,118001,United States,North America,53,Gnardog CrossFit,426956,209.00000,69.000000,116564,f,None,392,110519,f,16:40,None,100206,f,9:31,None,99667,f,100
1,1,CHRIS,ZUCK,118002,United States,North America,37,The Pack CrossFit,426960,NaN,NaN,116854,f,None,167,110205,f,10:08,None,100367,f,11:25,None,99534,f,115
2,2,STEPHEN,HUDEC,118002,United States,North America,31,CrossFit Proton,426960,187.39270,70.078740,116869,None,None,None,110327,f,12:44,None,99902,None,7:42,None,99862,f,66
3,3,SERGEY,KUPRIYANOV,118004,Russian Federation,Asia,33,Natrium CrossFit,426962,NaN,NaN,115764,s,None,118,110650,f,19:59,None,100553,s,None,151,99995,f,35
4,4,CARLOS,RIVEIRO VILLANUEVA,118005,Spain,Europe,18,CrossFit Ponferrada,426965,NaN,NaN,117347,None,None,None,92388,None,None,145,101151,None,None,None,116079,None,None
5,5,PRASIT,MANKAD,118006,Australia,Oceania,41,CrossFit Richmond,426975,NaN,NaN,117347,None,None,None,104270,s,None,218,101151,None,None,None,104207,None,None
6,6,MATTHEW,FIACCO,118007,Canada,North America,33,CrossFit Okanagan,426980,NaN,NaN,116816,f,None,217,110496,f,16:13,None,100075,f,8:37,None,99593,f,110
7,7,JIM,LIEN,118007,United States,North America,54,NaN,426980,NaN,NaN,116387,f,None,569,110414,f,14:26,None,100176,f,9:15,None,100003,f,30
8,8,ABRIE,SCHUTTE,118009,United Kingdom,Europe,38,CrossFit Blackwater,426984,302.03294,72.047244,115580,s,None,209,110754,None,None,None,100569,s,None,None,100081,None,None
9,9,ABDULLAH,ALSHAIKH,118010,Saudi Arabia,Asia,35,Interval Plus CrossFit,426986,198.41580,71.259843,114856,s,None,215,111374,None,None,None,96549,s,None,110,104207,s,0
10,10,OCTAVIO,RODRIGUEZ,118011,Colombia,South America,51,CrossFit Willemstad,426991,238.00000,73.228346,112603,s,None,304,106374,s,None,200,101151,s,None,None,106863,None,None
11,11,JEFF,DENBY,118012,Canada,North America,43,CrossFit Vastberaden,426998,168.00000,70.000000,116869,None,None,None,74271,None,None,194,101151,None,None,None,134707,None,None
12,12,TYANOH,CORTE REAL-ROSA,118013,Australia,Oceania,25,NaN,427001,NaN,NaN,103726,s,None,468,108638,s,None,164,101151,s,None,None,113486,None,None
13,13,MAËL,SANTIER,118014,France,Europe,20,Luçon CrossFit,427006,NaN,NaN,116869,None,None,None,110615,f,18:57,None,99942,None,7:55,None,99580,f,110
14,14,PAUL,HOECK,118015,United States,North America,39,CrossFit Strong Island,427008,310.00000,76.000000,104950,s,None,395,88609,None,None,158,101151,s,None,None,132298,None,None
15,15,MATTHEW,SHERMAN,118015,United States,North America,42,CrossFit Contrivance,427008,245.00000,73.000000,116601,f,None,386,110479,f,15:51,None,100442,f,13:05,None,99486,f,120
16,16,DANIE,VAN ZYL,118015,South Africa,Africa,38,CrossFit Richards Bay,427008,NaN,NaN,116623,f,None,384,110366,f,13:42,None,100334,f,10:58,None,99685,f,99
17,17,JASON,WEBSTER,118018,United Kingdom,Europe,51,Unit 22 CrossFit Northampton,427017,198.00000,71.000000,98242,s,13:14,None,96104,s,14:23,None,101151,s,None,None,131520,None,None
18,18,JOHN,ROBINSON,118019,United States,North America,36,Dignified CrossFit,427019,NaN,NaN,98415,s,13:21,None,111374,None,None,None,101151,s,None,None,116079,None,None
19,19,ANTHONY,SWARTZ,118020,Namibia,Africa,42,CrossFit Damascus,427025,251.32668,66.929134,116605,f,None,386,110532,f,16:55,None,100281,f,10:10,None,99607,f,110
20,20,SEBASTIAN,JOHNSON,118021,United States,North America,47,CrossFit Proprius,427027,187.00000,72.000000,116506,f,None,445,110334,f,12:52,None,100360,f,11:17,None,99827,f,75
21,21,HARRY,DAVIS,118022,Australia,Oceania,46,CrossFit Shoalhaven,427030,200.62042,70.078740,93363,None,None,47,111374,None,None,None,101151,None,None,None,121142,None,None
22,22,BENITO,REQUENA,118023,Spain,Europe,23,Dagaz CrossFit,427032,NaN,NaN,116776,f,None,250,109963,s,None,120,100380,f,11:39,None,99913,f,55
23,23,MARK,HICKS,118024,United Kingdom,Europe,34,Reebok CrossFit Cardiff,427034,NaN,NaN,116869,None,None,None,87872,None,None,160,101151,None,None,None,121142,None,None
24,24,ADAM,UPTON,118025,Australia,Oceania,41,NaN,427038,253.53130,74.015748,101027,s,14:46,None,111374,None,None,None,101151,s,None,None,113486,None,None
25,25,JAVIER,BELLAS,118026,Spain,Europe,34,CrossFit SBB Jungle,427041,NaN,NaN,99345,s,13:55,None,97141,s,15:40,None,101151,s,None,None,129404,None,None
26,26,BENJAMIN,GORDON,118026,United States,North America,35,NaN,427041,NaN,68.000000,116732,f,None,302,110000,s,None,115,100504,f,14:34,None,99805,f,81
27,27,BEN,CRAVEN,118028,United Kingdom,Europe,16,CrossFit Leyland,427046,NaN,NaN,116477,f,None,475,110555,f,17:18,None,100012,f,8:20,None,100002,f,30
28,28,MOSTAFA,FAYEK,118029,United States,North America,54,CrossFit Perception,427053,NaN,NaN,116677,f,None,375,110579,f,17:56,None,100162,f,9:11,None,99635,f,105
29,29,GRAHAM,SMITH,118030,New Zealand,Oceania,53,CrossFit Trailblazer,427057,165.34650,66.929134,98056,s,13:07,None,111374,None,None,None,101151,s,None,None,116476,None,None
30,30,DANIEL,WALSH,118031,United States,North America,45,CrossFit Blackbeard,427060,220.00000,67.000000,112564,s,None,309,107581,s,None,183,101151,s,None,None,105764,None,None
31,31,JANOS,TOTH,118032,Hungary,Europe,38,NaN,427062,178.57422,71.653543,116300,f,14:21,None,110624,f,19:21,None,100304,f,10:30,None,99834,f,72
32,32,JOHN,GRAHAM,118033,United States,North America,39,TBE CrossFit,427063,170.00000,68.000000,98889,s,13:39,None,111374,None,None,None,101151,s,None,None,115649,None,None
33,33,JASON,STEVENS,118033,Australia,Oceania,37,CrossFit Iron Lion,427063,216.05276,70.078740,116684,f,None,374,110387,f,13:58,None,100156,f,9:07,None,99836,f,71
34,34,ABDULLA,ALDARWISH,118035,Qatar,Asia,29,CrossFit Erada,427067,211.64352,66.929134,114727,s,None,215,87501,None,None,161,101151,s,None,None,123688,None,None
35,35,HIROKI,NAGAI,118035,Japan,Asia,49,CrossFit Kumamoto,427067,NaN,NaN,116620,f,None,384,110281,f,11:48,None,100314,f,10:40,None,99852,f,67
36,36,BASHAR,ALKHAFAJI,118037,Iraq,Asia,44,NaN,427068,198.41580,68.110236,116623,f,None,384,110567,f,17:40,None,100272,f,10:02,None,99606,f,110
37,37,CHRISTOPHER,NEWTON,118038,Canada,North America,42,TRC CrossFit,427069,NaN,NaN,110337,s,None,379,111374,None,None,None,101151,s,None,None,104207,None,None
38,38,ROCKY,MENDIOLA,118039,United States,North America,43,Burg CrossFit North,427076,205.00000,70.000000,110344,s,None,379,111374,None,None,None,101151,s,None,None,104207,None,None
39,39,IAGO,PORTO,118040,Brazil,South America,23,Paracatu CrossFit,427078,200.62042,77.165354,110802,s,None,377,90262,None,None,152,101151,s,None,None,124863,None,None